In [322]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [323]:
#Process the raw data output and fill NA values with 0.
data = pd.read_excel ("data/2019-02-27_161601 AtWAKL8 different version expressions.xls",
                     sheet_name='Results').fillna(0)
data.head(3)

,Block Type,384-Well Block,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,Calibration Background is expired,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Calibration Background performed on,12-19-2018,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Calibration Pure Dye ABY is expired,No,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [324]:
# iloc[row slicing, column slicing]
data = data.iloc[46:191, 3:15]

#Create a new header row for the columns
data = data.rename(columns=data.iloc[0]).drop(data.index[0])

#Omit all columns except for "Sample Name", "Target Name" and "CT"
data = data[['Sample Name', 'Target Name', 'CT']]
data.reset_index(drop=True)
data.head(3)

   Sample Name Target Name       CT
47         WT1   AtTubulin  23.3577
48         WT1   AtTubulin  24.0598
49         WT1   AtTubulin  23.0126

# Save to file options:

## for .csv
#### data.to_csv('data/processed1.csv', index = False)

## for .xlsx
#### data.to_excel('data/processed1.xlsx', index = False)

## for .txt (tab delimited)
#### data.to_csv('data/processed1.txt', index = False, sep = '\t')

In [325]:
data.to_csv('data/processed1.csv', index = False)

In [326]:
df1 = pd.read_csv('data/processed1.csv')
df1.loc[df1['Sample Name'].str.contains('WT')]

    Sample Name  Target Name                  CT
0           WT1    AtTubulin  23.357698440551758
1           WT1    AtTubulin   24.05980110168457
2           WT1    AtTubulin  23.012556076049805
12          WT1      AtGADPH  21.092479705810547
13          WT1      AtGADPH  22.244646072387695
14          WT1      AtGADPH  21.961414337158203
24          WT1       WAKL8A  29.440208435058594
25          WT1       WAKL8A  29.623292922973633
26          WT1       WAKL8A   27.98357582092285
36          WT1  WAKL8 Total  24.960891723632812
37          WT1  WAKL8 Total  24.934545516967773
38          WT1  WAKL8 Total  24.978439331054688
48          WT2    AtTubulin  22.741384506225586
49          WT2    AtTubulin  22.596120834350586
50          WT2    AtTubulin      22.32861328125
60          WT2      AtGADPH  20.884580612182617
61          WT2      AtGADPH  20.880754470825195
62          WT2      AtGADPH  20.507720947265625
72          WT2       WAKL8A  27.515586853027344
73          WT2       WAKL8A  27.158470153808594
74          WT2       WAKL8A  27.158802032470703
84          WT2  WAKL8 Total  24.847976684570312
85          WT2  WAKL8 Total   24.39812469482422
86          WT2  WAKL8 Total   24.45286750793457
96          WT3    AtTubulin  22.129268646240234
97          WT3    AtTubulin   21.89289093017578
98          WT3    AtTubulin  21.960674285888672
108         WT3      AtGADPH  20.447322845458984
109         WT3      AtGADPH  20.644203186035156
110         WT3      AtGADPH  21.010990142822266
120         WT3       WAKL8A  28.056936264038086
121         WT3       WAKL8A   28.28282928466797
122         WT3       WAKL8A  28.363048553466797
132         WT3  WAKL8 Total  25.073081970214844
133         WT3  WAKL8 Total  25.057270050048828
134         WT3  WAKL8 Total  25.216686248779297

In [327]:
#display all 'Sample Names' that contain str 'WT' or str 'wakl8-1'

import re
df1.loc[df1['Sample Name'].str.contains('WT|wakl8-1', flags=re.I, regex=True)]

    Sample Name  Target Name                  CT
0           WT1    AtTubulin  23.357698440551758
1           WT1    AtTubulin   24.05980110168457
2           WT1    AtTubulin  23.012556076049805
6     wakl8-1-1    AtTubulin     24.074462890625
7     wakl8-1-1    AtTubulin   24.60406494140625
8     wakl8-1-1    AtTubulin  23.958826065063477
12          WT1      AtGADPH  21.092479705810547
13          WT1      AtGADPH  22.244646072387695
14          WT1      AtGADPH  21.961414337158203
18    wakl8-1-1      AtGADPH  21.272266387939453
19    wakl8-1-1      AtGADPH   21.66851806640625
20    wakl8-1-1      AtGADPH  21.398895263671875
24          WT1       WAKL8A  29.440208435058594
25          WT1       WAKL8A  29.623292922973633
26          WT1       WAKL8A   27.98357582092285
30    wakl8-1-1       WAKL8A        25.779296875
31    wakl8-1-1       WAKL8A  25.688945770263672
32    wakl8-1-1       WAKL8A  25.850378036499023
36          WT1  WAKL8 Total  24.960891723632812
37          WT1  WAKL8 Total  24.934545516967773
38          WT1  WAKL8 Total  24.978439331054688
42    wakl8-1-1  WAKL8 Total  23.995759963989258
43    wakl8-1-1  WAKL8 Total  23.792034149169922
44    wakl8-1-1  WAKL8 Total  23.721040725708008
48          WT2    AtTubulin  22.741384506225586
49          WT2    AtTubulin  22.596120834350586
50          WT2    AtTubulin      22.32861328125
54    wakl8-1-2    AtTubulin  22.977094650268555
55    wakl8-1-2    AtTubulin  23.619104385375977
56    wakl8-1-2    AtTubulin  23.794626235961914
..          ...          ...                 ...
84          WT2  WAKL8 Total  24.847976684570312
85          WT2  WAKL8 Total   24.39812469482422
86          WT2  WAKL8 Total   24.45286750793457
90    wakl8-1-2  WAKL8 Total    24.3045597076416
91    wakl8-1-2  WAKL8 Total   24.52280616760254
92    wakl8-1-2  WAKL8 Total  24.398895263671875
96          WT3    AtTubulin  22.129268646240234
97          WT3    AtTubulin   21.89289093017578
98          WT3    AtTubulin  21.960674285888672
102   wakl8-1-3    AtTubulin  22.171350479125977
103   wakl8-1-3    AtTubulin  22.183456420898438
104   wakl8-1-3    AtTubulin  22.646684646606445
108         WT3      AtGADPH  20.447322845458984
109         WT3      AtGADPH  20.644203186035156
110         WT3      AtGADPH  21.010990142822266
114   wakl8-1-3      AtGADPH  20.297452926635742
115   wakl8-1-3      AtGADPH  20.392925262451172
116   wakl8-1-3      AtGADPH  20.722400665283203
120         WT3       WAKL8A  28.056936264038086
121         WT3       WAKL8A   28.28282928466797
122         WT3       WAKL8A  28.363048553466797
126   wakl8-1-3       WAKL8A       26.2685546875
127   wakl8-1-3       WAKL8A  26.064273834228516
128   wakl8-1-3       WAKL8A   25.96087646484375
132         WT3  WAKL8 Total  25.073081970214844
133         WT3  WAKL8 Total  25.057270050048828
134         WT3  WAKL8 Total  25.216686248779297
138   wakl8-1-3  WAKL8 Total  23.458744049072266
139   wakl8-1-3  WAKL8 Total  23.606586456298828
140   wakl8-1-3  WAKL8 Total   23.53990364074707

[72 rows x 3 columns]

In [328]:
#display all 'Target Names' that contain str 'WAKL8 Total'

df1.loc[df1['Target Name'].str.contains ('WAKL8 Total', flags=re.I, regex=True)]

      Sample Name  Target Name                  CT
36            WT1  WAKL8 Total  24.960891723632812
37            WT1  WAKL8 Total  24.934545516967773
38            WT1  WAKL8 Total  24.978439331054688
39   fla11fla12-1  WAKL8 Total  22.078956604003906
40   fla11fla12-1  WAKL8 Total  22.372718811035156
41   fla11fla12-1  WAKL8 Total  22.265132904052734
42      wakl8-1-1  WAKL8 Total  23.995759963989258
43      wakl8-1-1  WAKL8 Total  23.792034149169922
44      wakl8-1-1  WAKL8 Total  23.721040725708008
45      wakl8-2-1  WAKL8 Total  26.763742446899414
46      wakl8-2-1  WAKL8 Total   27.49288558959961
47      wakl8-2-1  WAKL8 Total  26.989784240722656
84            WT2  WAKL8 Total  24.847976684570312
85            WT2  WAKL8 Total   24.39812469482422
86            WT2  WAKL8 Total   24.45286750793457
87   fla11fla12-2  WAKL8 Total  24.490589141845703
88   fla11fla12-2  WAKL8 Total  24.520193099975586
89   fla11fla12-2  WAKL8 Total   24.59166145324707
90      wakl8-1-2  WAKL8 Total    24.3045597076416
91      wakl8-1-2  WAKL8 Total   24.52280616760254
92      wakl8-1-2  WAKL8 Total  24.398895263671875
93      wakl8-2-2  WAKL8 Total  28.057058334350586
94      wakl8-2-2  WAKL8 Total     27.955810546875
95      wakl8-2-2  WAKL8 Total   27.94371223449707
132           WT3  WAKL8 Total  25.073081970214844
133           WT3  WAKL8 Total  25.057270050048828
134           WT3  WAKL8 Total  25.216686248779297
135  fla11fla12-3  WAKL8 Total  24.052894592285156
136  fla11fla12-3  WAKL8 Total  24.034820556640625
137  fla11fla12-3  WAKL8 Total   24.38533592224121
138     wakl8-1-3  WAKL8 Total  23.458744049072266
139     wakl8-1-3  WAKL8 Total  23.606586456298828
140     wakl8-1-3  WAKL8 Total   23.53990364074707
141     wakl8-2-3  WAKL8 Total   27.32314682006836
142     wakl8-2-3  WAKL8 Total  26.145767211914062
143     wakl8-2-3  WAKL8 Total  26.422136306762695

In [329]:
#display all 'Sample Names' that contain str 'WT' or all 'Target Names' that contain str 'Tub'

df1.loc[df1['Sample Name'].str.contains('WT')|df1['Target Name'].str.contains('Tub', flags=re.I, regex=True)]

      Sample Name  Target Name                  CT
0             WT1    AtTubulin  23.357698440551758
1             WT1    AtTubulin   24.05980110168457
2             WT1    AtTubulin  23.012556076049805
3    fla11fla12-1    AtTubulin  23.803699493408203
4    fla11fla12-1    AtTubulin  24.919694900512695
5    fla11fla12-1    AtTubulin  24.535173416137695
6       wakl8-1-1    AtTubulin     24.074462890625
7       wakl8-1-1    AtTubulin   24.60406494140625
8       wakl8-1-1    AtTubulin  23.958826065063477
9       wakl8-2-1    AtTubulin  22.542207717895508
10      wakl8-2-1    AtTubulin   22.19947624206543
11      wakl8-2-1    AtTubulin  22.908100128173828
12            WT1      AtGADPH  21.092479705810547
13            WT1      AtGADPH  22.244646072387695
14            WT1      AtGADPH  21.961414337158203
24            WT1       WAKL8A  29.440208435058594
25            WT1       WAKL8A  29.623292922973633
26            WT1       WAKL8A   27.98357582092285
36            WT1  WAKL8 Total  24.960891723632812
37            WT1  WAKL8 Total  24.934545516967773
38            WT1  WAKL8 Total  24.978439331054688
48            WT2    AtTubulin  22.741384506225586
49            WT2    AtTubulin  22.596120834350586
50            WT2    AtTubulin      22.32861328125
51   fla11fla12-2    AtTubulin  23.599971771240234
52   fla11fla12-2    AtTubulin  23.919401168823242
53   fla11fla12-2    AtTubulin  23.695655822753906
54      wakl8-1-2    AtTubulin  22.977094650268555
55      wakl8-1-2    AtTubulin  23.619104385375977
56      wakl8-1-2    AtTubulin  23.794626235961914
..            ...          ...                 ...
60            WT2      AtGADPH  20.884580612182617
61            WT2      AtGADPH  20.880754470825195
62            WT2      AtGADPH  20.507720947265625
72            WT2       WAKL8A  27.515586853027344
73            WT2       WAKL8A  27.158470153808594
74            WT2       WAKL8A  27.158802032470703
84            WT2  WAKL8 Total  24.847976684570312
85            WT2  WAKL8 Total   24.39812469482422
86            WT2  WAKL8 Total   24.45286750793457
96            WT3    AtTubulin  22.129268646240234
97            WT3    AtTubulin   21.89289093017578
98            WT3    AtTubulin  21.960674285888672
99   fla11fla12-3    AtTubulin   22.98185920715332
100  fla11fla12-3    AtTubulin  22.853368759155273
101  fla11fla12-3    AtTubulin   23.41008949279785
102     wakl8-1-3    AtTubulin  22.171350479125977
103     wakl8-1-3    AtTubulin  22.183456420898438
104     wakl8-1-3    AtTubulin  22.646684646606445
105     wakl8-2-3    AtTubulin   23.74367332458496
106     wakl8-2-3    AtTubulin  23.487897872924805
107     wakl8-2-3    AtTubulin   23.25385856628418
108           WT3      AtGADPH  20.447322845458984
109           WT3      AtGADPH  20.644203186035156
110           WT3      AtGADPH  21.010990142822266
120           WT3       WAKL8A  28.056936264038086
121           WT3       WAKL8A   28.28282928466797
122           WT3       WAKL8A  28.363048553466797
132           WT3  WAKL8 Total  25.073081970214844
133           WT3  WAKL8 Total  25.057270050048828
134           WT3  WAKL8 Total  25.216686248779297

[63 rows x 3 columns]

In [ ]:
#Calculate mean 'CT' for all 'Sample Name' repeats

In [341]:
#

df1.groupby(df1['Target Name'])

In [ ]:
#Still need to work out:

In [ ]:
#Subtract the housekeeping Target genes ("AtTubulin", "AtGADPH") CT value from the genes of interest CT value